{"name": "test_auth", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: headless chrome=101.0.4951.64)\nStacktrace:\n#0 0x564c5bf63533 <unknown>\n#1 0x564c5bcc207f <unknown>\n#2 0x564c5bcf93a7 <unknown>\n#3 0x564c5bced4a9 <unknown>\n#4 0x564c5bd15f42 <unknown>\n#5 0x564c5bcecd63 <unknown>\n#6 0x564c5bd1604e <unknown>\n#7 0x564c5bd29224 <unknown>\n#8 0x564c5bd15e33 <unknown>\n#9 0x564c5bceb71a <unknown>\n#10 0x564c5bcec875 <unknown>\n#11 0x564c5bfa7e1d <unknown>\n#12 0x564c5bfab751 <unknown>\n#13 0x564c5bf9207e <unknown>\n#14 0x564c5bfac388 <unknown>\n#15 0x564c5bf86fe0 <unknown>\n#16 0x564c5bfc8748 <unknown>\n#17 0x564c5bfc88c8 <unknown>\n#18 0x564c5bfe270d <unknown>\n#19 0x7f977db363ba <unknown>\n#20 0x7f977d5cf393 <unknown>", "trace": "tests/test_auth.py:12: in test_auth\n    main_page.authorization()\n        browser    = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"340827a2799485ea4909ac1656dece0f\")>\n        main_page  = <pages.MainPage.MainPageHelper object at 0x7fa9aa6dea60>\npages/MainPage.py:29: in authorization\n    auth_button.click()\n        auth_button = <selenium.webdriver.remote.webelement.WebElement (session=\"340827a2799485ea4909ac1656dece0f\", element=\"43debd60-b6b2-4182-abfd-3f4c4e7cae22\")>\n        dialog_window = <selenium.webdriver.remote.webelement.WebElement (session=\"340827a2799485ea4909ac1656dece0f\", element=\"84f31f02-c217-45ff-ab0e-c71946d35518\")>\n        excape     = <selenium.webdriver.remote.webelement.WebElement (session=\"340827a2799485ea4909ac1656dece0f\", element=\"a693c7d6-6146-45b7-9efc-e6132d205d97\")>\n        self       = <pages.MainPage.MainPageHelper object at 0x7fa9aa6dea60>\nvenv/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py:89: in click\n    self._execute(Command.CLICK_ELEMENT)\n        self       = <selenium.webdriver.remote.webelement.WebElement (session=\"340827a2799485ea4909ac1656dece0f\", element=\"43debd60-b6b2-4182-abfd-3f4c4e7cae22\")>\nvenv/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py:773: in _execute\n    return self._parent.execute(command, params)\n        command    = 'clickElement'\n        params     = {'id': '43debd60-b6b2-4182-abfd-3f4c4e7cae22', 'sessionId': '340827a2799485ea4909ac1656dece0f'}\n        self       = <selenium.webdriver.remote.webelement.WebElement (session=\"340827a2799485ea4909ac1656dece0f\", element=\"43debd60-b6b2-4182-abfd-3f4c4e7cae22\")>\nvenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:430: in execute\n    self.error_handler.check_response(response)\n        driver_command = 'clickElement'\n        params     = {'id': '43debd60-b6b2-4182-abfd-3f4c4e7cae22'}\n        response   = {'status': 400, 'value': '{\"value\":{\"error\":\"element not interactable\",\"message\":\"element not interactable\\\\n  (Sessio...\\\\n#18 0x564c5bfe270d \\\\u003Cunknown>\\\\n#19 0x7f977db363ba \\\\u003Cunknown>\\\\n#20 0x7f977d5cf393 \\\\u003Cunknown>\\\\n\"}}'}\n        self       = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"340827a2799485ea4909ac1656dece0f\")>\nvenv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:247: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\nE     (Session info: headless chrome=101.0.4951.64)\nE   Stacktrace:\nE   #0 0x564c5bf63533 <unknown>\nE   #1 0x564c5bcc207f <unknown>\nE   #2 0x564c5bcf93a7 <unknown>\nE   #3 0x564c5bced4a9 <unknown>\nE   #4 0x564c5bd15f42 <unknown>\nE   #5 0x564c5bcecd63 <unknown>\nE   #6 0x564c5bd1604e <unknown>\nE   #7 0x564c5bd29224 <unknown>\nE   #8 0x564c5bd15e33 <unknown>\nE   #9 0x564c5bceb71a <unknown>\nE   #10 0x564c5bcec875 <unknown>\nE   #11 0x564c5bfa7e1d <unknown>\nE   #12 0x564c5bfab751 <unknown>\nE   #13 0x564c5bf9207e <unknown>\nE   #14 0x564c5bfac388 <unknown>\nE   #15 0x564c5bf86fe0 <unknown>\nE   #16 0x564c5bfc8748 <unknown>\nE   #17 0x564c5bfc88c8 <unknown>\nE   #18 0x564c5bfe270d <unknown>\nE   #19 0x7f977db363ba <unknown>\nE   #20 0x7f977d5cf393 <unknown>\n        exception_class = <class 'selenium.common.exceptions.ElementNotInteractableException'>\n        json       = <module 'json' from '/usr/lib/python3.9/json/__init__.py'>\n        message    = 'element not interactable\\n  (Session info: headless chrome=101.0.4951.64)'\n        response   = {'status': 400, 'value': '{\"value\":{\"error\":\"element not interactable\",\"message\":\"element not interactable\\\\n  (Sessio...\\\\n#18 0x564c5bfe270d \\\\u003Cunknown>\\\\n#19 0x7f977db363ba \\\\u003Cunknown>\\\\n#20 0x7f977d5cf393 \\\\u003Cunknown>\\\\n\"}}'}\n        screen     = None\n        self       = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fa9aa786ca0>\n        st_value   = '#0 0x564c5bf63533 <unknown>\\n#1 0x564c5bcc207f <unknown>\\n#2 0x564c5bcf93a7 <unknown>\\n#3 0x564c5bced4a9 <unknown>\\n#...7 0x564c5bfc88c8 <unknown>\\n#18 0x564c5bfe270d <unknown>\\n#19 0x7f977db363ba <unknown>\\n#20 0x7f977d5cf393 <unknown>\\n'\n        stacktrace = ['#0 0x564c5bf63533 <unknown>', '#1 0x564c5bcc207f <unknown>', '#2 0x564c5bcf93a7 <unknown>', '#3 0x564c5bced4a9 <unknown>', '#4 0x564c5bd15f42 <unknown>', '#5 0x564c5bcecd63 <unknown>', ...]\n        status     = 'element not interactable'\n        value      = {'error': 'element not interactable', 'message': 'element not interactable\\n  (Session info: headless chrome=101.0.495... 0x564c5bfc88c8 <unknown>\\n#18 0x564c5bfe270d <unknown>\\n#19 0x7f977db363ba <unknown>\\n#20 0x7f977d5cf393 <unknown>\\n'}\n        value_json = '{\"value\":{\"error\":\"element not interactable\",\"message\":\"element not interactable\\\\n  (Session info: headless chrome=1...>\\\\n#18 0x564c5bfe270d \\\\u003Cunknown>\\\\n#19 0x7f977db363ba \\\\u003Cunknown>\\\\n#20 0x7f977d5cf393 \\\\u003Cunknown>\\\\n\"}}'"}, "attachments": [{"name": "stdout", "source": "0236259a-e0df-4512-ae07-e9865ef79947-attachment.txt", "type": "text/plain"}], "start": 1653900435004, "stop": 1653900439580, "uuid": "d545d250-6c8c-44f5-8125-1c61064830de", "historyId": "e701bae96da603ae7345ed8f71bbc3db", "testCaseId": "5306df55395c93b83e69abe887b683bd", "fullName": "tests.test_auth#test_auth", "labels": [{"name": "feature", "value": "Авторизация на платформе"}, {"name": "severity", "value": "blocker"}, {"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "fedora"}, {"name": "thread", "value": "19700-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}